<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="USMUMAANNALDAS2" name="Check Before Test and Before Class" tests="3" failures="1" timestamp="1 Oct 2016 09:09:28 GMT" time="4.057" errors="0">
  <testcase name="" time="4.014" classname="BeforeTest_BeforeClass.Class1">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.Method1() didn&amp;apos;t finish within the time-out 4000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.Method1() didn't finish within the time-out 4000
	at java.util.concurrent.FutureTask.setException(FutureTask.java:248)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!--  -->
  <testcase name="Method3" time="0.003" classname="BeforeTest_BeforeClass.Class2"/>
  <testcase name="Method4" time="0.003" classname="BeforeTest_BeforeClass.Class2"/>
</testsuite> <!-- Check Before Test and Before Class -->
